import { readdir, writeFile, readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Emit the @font-face rules for Avenir Arabic from whatever font files are
 * actually sitting in public/fonts.
 *
 * Avenir Arabic is a licensed Monotype typeface. It is not on Google Fonts and
 * it is not in this repository, so the rules cannot simply be written by hand
 * and committed: a @font-face pointing at a file that is not there would make
 * every page request a font that does not exist, and because vercel.json
 * rewrites unknown paths to /index.html, the browser would receive an HTML
 * document with a 200 status where it asked for a font — a wasted download on
 * every visit, not even an honest 404.
 *
 * So the stylesheet is generated instead. With no font files present it is a
 * comment and nothing else, and the site renders in the fallback faces that
 * are already committed. Drop the licensed .woff2 files into public/fonts and
 * the next build wires them up with no code change anywhere.
 *
 * Filenames are read rather than dictated, because the files arrive named
 * however the foundry named them: AvenirArabic-Book.woff2, avenir-arabic-700,
 * Avenir Arabic Heavy — all understood. Anything with "avenir" in the name is
 * a candidate; the weight is whatever weight word or number the name carries.
 */

const here = path.dirname(fileURLToPath(import.meta.url));
const FONT_DIR = path.join(here, "public/fonts");
const OUT = path.join(FONT_DIR, "avenir-arabic.css");

/** The family name the CSS declares, and the one index.css asks for. */
const FAMILY = "Avenir Arabic";

/** Weight words a foundry might use, mapped to the numbers CSS wants. */
const WEIGHT_WORDS = {
  thin: 100, hairline: 100,
  extralight: 200, ultralight: 200,
  light: 300,
  book: 400, regular: 400, roman: 400, normal: 400,
  medium: 500,
  semibold: 600, demibold: 600, demi: 600,
  bold: 700,
  heavy: 800, extrabold: 800, ultrabold: 800,
  black: 900, ultra: 900,
};

/** woff2 first: every browser that matters takes it, and it is the smallest. */
const FORMATS = [
  [".woff2", "woff2"],
  [".woff", "woff"],
  [".otf", "opentype"],
  [".ttf", "truetype"],
];

function classify(filename) {
  const ext = path.extname(filename).toLowerCase();
  const format = FORMATS.find(([e]) => e === ext)?.[1];
  if (!format) return null;

  const stem = path.basename(filename, ext).toLowerCase();
  if (!stem.includes("avenir")) return null;

  // Drop the family part so "Avenir Arabic Black" does not read as weight 400
  // via the "arabic" -> nothing, but also so a family word never shadows a
  // weight word. What is left is the style description.
  const rest = stem
    .replace(/avenir/g, " ")
    .replace(/arabic/g, " ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

  const italic = /\b(italic|oblique)\b/.test(rest);

  const numeric = rest.match(/\b([1-9]00)\b/);
  let weight = numeric ? Number(numeric[1]) : null;
  if (weight === null) {
    // Longest word first, so "extralight" is not read as "light".
    for (const word of Object.keys(WEIGHT_WORDS).sort((a, b) => b.length - a.length)) {
      if (rest.includes(word)) {
        weight = WEIGHT_WORDS[word];
        break;
      }
    }
  }
  // A file with no weight in its name is the regular one — that is what a bare
  // "AvenirArabic.woff2" means.
  if (weight === null) weight = 400;

  return { weight, italic, format, filename };
}

const HEADER = `/*
 * Avenir Arabic — generated by fonts-avenir.mjs. Do not edit by hand.
 *
 * Regenerated on every build from the font files present in public/fonts.
 */
`;

const EMPTY = `${HEADER}
/*
 * No Avenir Arabic font files found in public/fonts.
 *
 * This file is deliberately empty rather than absent: index.html links it
 * unconditionally, and a missing stylesheet would be answered by the SPA
 * rewrite with an HTML document.
 *
 * To make Avenir Arabic live, drop the licensed webfont files here — e.g.
 * AvenirArabic-Book.woff2, AvenirArabic-Medium.woff2, AvenirArabic-Heavy.woff2
 * — and build. Until then the site renders in the fallback faces named after
 * Avenir Arabic in index.css, which is why nothing looks broken meanwhile.
 */
`;

async function main() {
  let entries = [];
  try {
    entries = await readdir(FONT_DIR);
  } catch {
    console.error(`[fonts] ${FONT_DIR} does not exist`);
    process.exitCode = 1;
    return;
  }

  const faces = entries.map(classify).filter(Boolean);

  if (faces.length === 0) {
    const existing = await readFile(OUT, "utf8").catch(() => null);
    if (existing !== EMPTY) await writeFile(OUT, EMPTY, "utf8");
    console.log("[fonts] no Avenir Arabic files in public/fonts — site stays on the fallback faces");
    return;
  }

  // One @font-face per weight/style, listing every format found for it.
  const groups = new Map();
  for (const face of faces) {
    const key = `${face.weight}-${face.italic ? "italic" : "normal"}`;
    if (!groups.has(key)) groups.set(key, { weight: face.weight, italic: face.italic, files: [] });
    groups.get(key).files.push(face);
  }

  const blocks = [...groups.values()]
    .sort((a, b) => a.weight - b.weight || Number(a.italic) - Number(b.italic))
    .map(({ weight, italic, files }) => {
      const src = files
        .sort(
          (a, b) =>
            FORMATS.findIndex(([, f]) => f === a.format) -
            FORMATS.findIndex(([, f]) => f === b.format),
        )
        // Quoted and percent-encoded: foundry files arrive with spaces in
        // their names ("Avenir Arabic Black Italic.woff"), and an unquoted
        // url() containing a space is not valid CSS — the whole rule is
        // dropped, silently.
        .map((f) => `url("/fonts/${encodeURI(f.filename)}") format('${f.format}')`)
        .join(",\n       ");
      // No unicode-range: these files are not subset, so claiming a range
      // would tell the browser not to use them for characters they cover.
      return `@font-face {
  font-family: '${FAMILY}';
  font-style: ${italic ? "italic" : "normal"};
  font-weight: ${weight};
  font-display: swap;
  src: ${src};
}`;
    });

  await writeFile(OUT, `${HEADER}\n${blocks.join("\n\n")}\n`, "utf8");

  const summary = [...groups.values()]
    .map((g) => `${g.weight}${g.italic ? "i" : ""}`)
    .sort()
    .join(", ");
  console.log(`[fonts] Avenir Arabic: ${groups.size} face(s) wired up (${summary})`);
  console.log(
    "[fonts] consider preloading the weights the first screen uses in index.html, " +
      "and dropping the tajawal/noto preloads once nothing renders in them",
  );
}

await main();
