import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import enrollRouter from "./enroll.js";
import authRouter from "./auth.js";
import workbookOrderRouter from "./workbook-order.js";
import adminRouter from "./admin.js";
import adminIntegrationsRouter from "./admin-integrations.js";
import consultationRouter from "./consultation.js";
import coursesRouter from "./courses.js";
import ordersRouter from "./orders.js";
import assignmentsRouter from "./assignments.js";
import speechEvaluationRouter from "./speech-evaluation.js";
import siteSettingsRouter from "./site-settings.js";
import cmsRouter from "./cms.js";
import certificatesRouter from "./certificates.js";
import chatRouter from "./chat.js";
import notificationsRouter from "./notifications.js";
import leadsRouter from "./leads.js";
import tasksRouter from "./tasks.js";
import automationsRouter from "./automations.js";
import messageTemplatesRouter from "./message-templates.js";
import funnelsRouter from "./funnels.js";
import growthRouter from "./growth.js";
import platformRouter from "./platform.js";
import attendanceRouter from "./attendance.js";
import activitiesRouter, { bootstrapActivities } from "./activities.js";
import littleSpeakerRouter from "./little-speaker.js";
import accreditationsRouter from "./accreditations.js";
import csrfRouter from "./csrf.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(csrfRouter);
router.use(authRouter);
router.use(enrollRouter);
router.use(workbookOrderRouter);
router.use(adminRouter);
router.use(adminIntegrationsRouter);
router.use(consultationRouter);
router.use(coursesRouter);
router.use(ordersRouter);
router.use(assignmentsRouter);
router.use(speechEvaluationRouter);
router.use(siteSettingsRouter);
router.use(cmsRouter);
router.use(certificatesRouter);
router.use(chatRouter);
router.use(notificationsRouter);
router.use(leadsRouter);
router.use(tasksRouter);
router.use(automationsRouter);
router.use(messageTemplatesRouter);
router.use(funnelsRouter);
router.use(growthRouter);
router.use(platformRouter);
router.use(attendanceRouter);
router.use(activitiesRouter);
router.use(littleSpeakerRouter);
router.use(accreditationsRouter);

// Run idempotent activities bootstrap (seed badges, convert legacy lessons)
void bootstrapActivities();

export default router;
