import { Router, type IRouter } from "express";
import healthRouter from "./health";
import enrollRouter from "./enroll";
import authRouter from "./auth";
import workbookOrderRouter from "./workbook-order";
import adminRouter from "./admin";
import adminIntegrationsRouter from "./admin-integrations";
import consultationRouter from "./consultation";
import coursesRouter from "./courses";
import ordersRouter from "./orders";
import assignmentsRouter from "./assignments";
import speechEvaluationRouter from "./speech-evaluation";
import siteSettingsRouter from "./site-settings";
import cmsRouter from "./cms";
import certificatesRouter from "./certificates";
import chatRouter from "./chat";
import notificationsRouter from "./notifications";
import leadsRouter from "./leads";
import tasksRouter from "./tasks";
import automationsRouter from "./automations";
import messageTemplatesRouter from "./message-templates";
import funnelsRouter from "./funnels";
import growthRouter from "./growth";
import platformRouter from "./platform";
import attendanceRouter from "./attendance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(enrollRouter);
router.use(workbookOrderRouter);
router.use(adminRouter);
router.use(adminIntegrationsRouter);
router.use(consultationRouter);
router.use(coursesRouter);
router.use(ordersRouter);
router.use(assignmentsRouter);
router.use(speechEvaluationRouter);
router.use(siteSettingsRouter);
router.use(cmsRouter);
router.use(certificatesRouter);
router.use(chatRouter);
router.use(notificationsRouter);
router.use(leadsRouter);
router.use(tasksRouter);
router.use(automationsRouter);
router.use(messageTemplatesRouter);
router.use(funnelsRouter);
router.use(growthRouter);
router.use(platformRouter);
router.use(attendanceRouter);

export default router;
