import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/pg-core";
import { usersTable } from "./auth";
import { coursesTable, lessonsTable } from "./lms";

// ── Live (Zoom) sessions per lesson ─────────────────────────────────────
// One row per lesson that has a scheduled live class. Trainers/admins set
// the join URL + scheduled time; students see "upcoming live session"
// cards on their dashboard.
export const liveSessionsTable = pgTable(
  "live_sessions",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    lessonId: varchar("lesson_id").notNull().references(() => lessonsTable.id, { onDelete: "cascade" }),
    zoomJoinUrl: varchar("zoom_join_url").notNull(),
    zoomMeetingId: varchar("zoom_meeting_id"),
    titleAr: varchar("title_ar"),
    scheduledAt: timestamp("scheduled_at", { withTimezone: true }).notNull(),
    durationMinutes: integer("duration_minutes").notNull().default(60),
    status: varchar("status", { length: 16 }).$type<"scheduled" | "live" | "ended" | "cancelled">().notNull().default("scheduled"),
    recordingUrl: varchar("recording_url"),
    createdById: varchar("created_by_id").references(() => usersTable.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  },
  (t) => [
    uniqueIndex("UQ_live_sessions_lesson").on(t.lessonId),
    index("IDX_live_sessions_scheduled").on(t.scheduledAt),
  ],
);

// ── Parent ↔ child links ────────────────────────────────────────────────
// A parent account can be linked to one or more student accounts via an
// invite code generated by the student/admin. status=pending until the
// parent redeems the code; then active.
export const parentLinksTable = pgTable(
  "parent_links",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    parentUserId: varchar("parent_user_id").references(() => usersTable.id, { onDelete: "cascade" }),
    studentUserId: varchar("student_user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
    inviteCode: varchar("invite_code", { length: 16 }).notNull(),
    status: varchar("status", { length: 16 }).$type<"pending" | "active" | "revoked">().notNull().default("pending"),
    relationshipAr: varchar("relationship_ar"),
    createdById: varchar("created_by_id").references(() => usersTable.id, { onDelete: "set null" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    activatedAt: timestamp("activated_at", { withTimezone: true }),
  },
  (t) => [
    uniqueIndex("UQ_parent_links_code").on(t.inviteCode),
    index("IDX_parent_links_parent").on(t.parentUserId),
    index("IDX_parent_links_student").on(t.studentUserId),
  ],
);

// ── Internal messaging (trainer ↔ student/parent, course broadcast) ─────
// Threads group a conversation. courseId optional = broadcast on a course;
// otherwise a 1:1 (or small group) thread. Participants list controls
// access. Distinct from the support `chat` system.
export const messageThreadsTable = pgTable(
  "message_threads",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    courseId: varchar("course_id").references(() => coursesTable.id, { onDelete: "set null" }),
    subject: varchar("subject").notNull(),
    isBroadcast: boolean("is_broadcast").notNull().default(false),
    createdById: varchar("created_by_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
    lastMessageAt: timestamp("last_message_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("IDX_message_threads_course").on(t.courseId),
    index("IDX_message_threads_recent").on(t.lastMessageAt),
  ],
);

export const messageThreadParticipantsTable = pgTable(
  "message_thread_participants",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    threadId: varchar("thread_id").notNull().references(() => messageThreadsTable.id, { onDelete: "cascade" }),
    userId: varchar("user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
    lastReadAt: timestamp("last_read_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex("UQ_thread_participants_thread_user").on(t.threadId, t.userId),
    index("IDX_thread_participants_user").on(t.userId),
  ],
);

export const platformMessagesTable = pgTable(
  "platform_messages",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    threadId: varchar("thread_id").notNull().references(() => messageThreadsTable.id, { onDelete: "cascade" }),
    senderId: varchar("sender_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
    body: text("body").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index("IDX_platform_messages_thread").on(t.threadId, t.createdAt),
  ],
);

export type LiveSession = typeof liveSessionsTable.$inferSelect;
export type NewLiveSession = typeof liveSessionsTable.$inferInsert;
export type ParentLink = typeof parentLinksTable.$inferSelect;
export type MessageThread = typeof messageThreadsTable.$inferSelect;
export type MessageThreadParticipant = typeof messageThreadParticipantsTable.$inferSelect;
export type PlatformMessage = typeof platformMessagesTable.$inferSelect;
